version: '3'

services:
  mysql:
    container_name: mysql-container
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  games-api:
    container_name: games-app-container
    image: jmorenobrasero3/internship-api:latest
    ports:
      - "80:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_INITIALIZATION-MODE=${SPRING_DATASOURCE_INITIALIZATION-MODE}